from probe import *
import copy
D={'sourceLanguage':'en','strings':{},'version':'1.0'}
def sub(n,label):return {'argNum':n,'formatSpecifier':'lld','variations':{'plural':{'one':su(label+' %arg single'),'other':su(label+' %arg many')}}}
# Same names appear in opposite textual order, explicit positional syntax.
en=su('Birds %1$#@BIRDS@ yards %2$#@YARDS@'); en['substitutions']={'BIRDS':sub(1,'EN birds'),'YARDS':sub(2,'EN yards')}
fr=su('Yards %2$#@YARDS@ oiseaux %1$#@BIRDS@'); fr['substitutions']={'YARDS':sub(2,'FR yards'),'BIRDS':sub(1,'FR birds')}
D['strings']['multi']=entry(en,fr)
D['strings']['auto']=entry(su('Generated'),su('Genere'));D['strings']['auto'].update({'comment':'Oracle generated note','isCommentAutoGenerated':True,'commentGenerationVersion':'1','generatesSymbol':False})
D['strings']['inline_text']=entry(su('Label %@ %lld **bold** <b>literal</b>'),su('Etiquette %2$lld %1$@ **gras** <b>texte</b>'))
stage('metadata-multi',D)
base=json.loads((P/'names-source.xcstrings').read_text());data={'sourceLanguage':'en','strings':{'target_only_substitution':base['strings']['target_only_substitution']},'version':'1.0'}
def remove_target(x):
 a=json.loads((R/'Localizable.xcstrings').read_text());a['strings']['target_only_substitution']['localizations'].pop('fr');write(R/'Localizable.xcstrings',a);write(R/'target-create-input.xcstrings',a)
stage('target-create',data,remove_target)
# Compiler validity and Xcode import preservation for minimal plurals and target-only simplification.
shape={'sourceLanguage':'en','strings':{
 'only_other':entry({'variations':{'plural':{'other':su('EN %lld')}}},{'variations':{'plural':{'other':su('FR %lld')}}}),
 'varied_source_simple_target':entry({'variations':{'plural':{'one':su('EN %lld one'),'other':su('EN %lld other')}}},su('FR %lld flat')),
},'version':'1.0'}
stage('shape-boundaries',shape)
# Insert standard XLIFF inline nodes into modified target to check actual import behavior.
inline={'sourceLanguage':'en','strings':{k:entry(su('source '+k),su('old '+k)) for k in ['g','ph','x']},'version':'1.0'}
def inline_mutate(x):
 t=E.parse(x)
 for u in t.findall('.//x:trans-unit',NS):
  k=u.attrib['id'];v=u.find('x:target',NS);v.text='before '
  c=E.SubElement(v,'{'+NS['x']+'}'+k,{'id':'1'});c.text=('%@' if k=='ph' else 'middle' if k=='g' else None);c.tail=' after'
 t.write(x,encoding='utf-8',xml_declaration=True)
stage('inline-import',inline,inline_mutate)
